# Generated by Django 2.1.4 on 2018-12-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181211_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_uploading',
            name='columns1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='索引名1'),
        ),
        migrations.AddField(
            model_name='file_uploading',
            name='columns2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='索引名2'),
        ),
        migrations.AddField(
            model_name='file_uploading',
            name='result',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='结果'),
        ),
        migrations.AddField(
            model_name='file_uploading',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='路由'),
        ),
        migrations.AlterField(
            model_name='file_uploading',
            name='file',
            field=models.FileField(upload_to='file', verbose_name='文件名'),
        ),
    ]
